#!/usr/bin/perl
use 5.18.2;
#ERbay Yigit
#yigit@neb.com May24, 2021

my $filename = "Book5.txt";
open(FH, '<', $filename) or die $!;

while(<FH>){
   if ($. > 1){
		my $line= $_;
		chomp($line);
		my ($type, $label, $mod, $modname, $id, $seq) = split('\t', $line);
		if ($type eq 'RNA'){
			$seq =~ s/\s+//g;   	 
			$seq =~ s{/[^/]*/}{}g; #THIS IS CORRECT BY TIMURE
			$seq =~ s/{\d+([^{}]*)}/$1/g;
			$seq =~ s/{([^{}]*)}/$1/g; # for {I}NNNNNN   	 
			$seq =~ s/[fmrg\(\)\*:]//g; 
			$seq =~ s/\d+//g;
			$seq =~ tr/Tt/UU/;
			say "$type\t$id\t$seq";
		}
	}
}


close(FH);
